### PR TITLE
Update payload.dd

### PR DESCRIPTION
**Pull request by H4K0N42**
Updated "Get Admin-Permission" part

### CODE REVIEW

**Comment by 0iphor13** [comment]
Just got here by accident lol.
ALT Y is wrong, it should be ALT y.
ALT Y = ALT SHIFT y
ALT y = ALT y

So this should be adapted :)

**Comment by dallaswinger** [comment]
> Just got here by accident lol. ALT Y is wrong, it should be ALT y. ALT Y = ALT SHIFT y ALT y = ALT y
> 
> So this should be adapted, then it works properly and you don't need to use the other method. :)

this is correct.

**Comment by dallaswinger** [comment]
@H4K0N42 if you still prefer to go ahead with this change I will merge as is

**Comment by H4K0N42** [comment]
Yes, please merge it @dallaswinger

**Pull request merged**
