### PR TITLE
Create WifiPasswordGrabber(WINDOWS)

### PR DESCRIPTION
**Pull request by Killer74-hub**
Grab Wfi Information from Wifi with cmd on Windows.

Note: you must script the last parts where you need to go to your E-mail and enter password and email automatically. Description in script.

### CODE REVIEW

**Comment by 0iphor13** [comment]
I saw your payload and you might wanna improve it. I don't think this will get approved like it is atm. Especially with the part "script it yourself"

**Comment by Killer74-hub** [comment]
Yeah, but when someone has another E-mail Inbox then they need to do it for themselves. Adjust the script if you want and show me what I could do.

> I saw your payload and you might wanna improve it. I don't think this will get approved like it is atm. Especially with the part "script it yourself"

**Comment by 0iphor13** [comment]
The thing is, you usually publish payloads and make them public so people can learn something and use them. So in your case, your payload is basically "dumping wifi profiles" & "write your own exfil method, probalby mail."

While for you, this might be straight forward, it is not for the end user. There are probably 30 different payloads dumping wifi profiles and exfiltrating them through different methods. 
So you wanted to use the e-mail way, totally legit way, even though I wouldn't recommed it.
So my recommendation then would be, as your way is very complicated, write it as an example with the hint that it may differ for different mail services. But in it's current state, most users would not even try to start.

And then, this ofc requires you to have a 2nd gen Ducky, usage of Duckyscript 3.0 and it's features. It will make your payload shorter, faster and more effecient. + easier to read. 

But these are just my personal opinions and recommendations. I hope you don't take this as an insult but as a try to help you.

**Comment by dallaswinger** [comment]
I agree with the above. Things that are configurable should be written with DEFINE statements, and at a minimum the payload should be "complete" in _some_ variation. As is, this payload is nonfunctional unless you follow vague instructions and write the rest yourself. 

Feel free to reopen after making changes.

**Pull request closed without merging**
