### PR TITLE
Created persistentReverseDucky

### PR DESCRIPTION
**Pull request by drapl0n**
Check out more at: https://github.com/drapl0n/persistentReverseDucky

### CODE REVIEW

**Comment by hak5darren** [comment]
Great contribution! Thanks! This will be added to the payloads.hak5.org library and entered into the payload award drawings.

**Comment by drapl0n** [comment]
Thanks!, I want to talk with you about another big payload i'm working you on, where can we do so?

**Comment by hak5darren** [comment]
@drapl0n Sounds awesome! I'm personally taking some time off for birthdays this week so am not as available as usual, but I do get to my hak5darren DMs on twitter as much as I can. Otherwise there's a lively group on discord -- https://community.hak5.org

**Comment by drapl0n** [comment]
@hak5darren I am already member of discord group, check out your DM whenever you get free and Advance Birthday Wishes to you!!

**Pull request merged**
