### PR TITLE
Create payload.txt

### PR DESCRIPTION
**Pull request by drapl0n**
**Dransomware** is USB Rubber Ducky Script with ransomware which will encrypt user's data without root privileges in 30 sec's.

### CODE REVIEW

**Comment by panicacid** [comment]
I don't believe you need to close and re PR if you're updating your code matey, any changes you make before the PR is merged will just update in the PR.

**Comment by drapl0n** [comment]
NO, I didn't changed code, many of guys who submitted PR after me got some sort of replies but I didn't therefore I re-submitted PR, sorry bud my bad

**Comment by panicacid** [comment]
> NO, I didn't changed code, many of guys who submitted PR after me got some sort of replies but I didn't therefore I re-submitted PR, sorry bud my bad

Ah yeah I just think the Devs are busy at the minute matey, I've got a PR waiting myself. Won't take em too long.

**Comment by drapl0n** [comment]
But guys who submitted PR after me, got merged in repo.

**Comment by foxtrot** [comment]
> But guys who submitted PR after me, got merged in repo.
Pull Requests are not reviewed and/or merged on a first come first serve basis. Your PR has a bad title, anyhow.

Unfortunately, we've decided to reject your pull request because we think adding ransomware payloads to the repository has no real redeeming quality but offers a large amount of consequences. It's hard to envision how this can be used in any non-negative way (similar to how we view phishing page submission for popular websites.

Thanks,
foxtrot

**Pull request closed without merging**
